modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="minenorthidentite"
version="1.0.0"
displayName="MineNorth Identité"
authors="MineNorth RP"
description='''Système d'identité MineNorth RP : carte d'identité, création définitive, présentation et réédition.''' 
[[dependencies.minenorthidentite]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.minenorthidentite]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.minenorthidentite]]
modId="minenorthapi"
mandatory=true
versionRange="[1.0.0,2)"
ordering="AFTER"
side="BOTH"
